---
title: "Manual curation trials"
date: 2025-07-14
format: html
---

# Comparing results of different TEammo curators

## Run BLASTs between curated libraries

```{bash}
mkdir -p results

# Make the blastdbs - they are output in same folder as the fasta input
conda activate MCHelper
while IFS=',' read -r species strain marta dean; do
  makeblastdb -in ${marta} -dbtype "nucl"
  #makeblastdb -in ${dean} -dbtype "nucl"
done < <(sed '1d' curated_libs.csv)

# Run BLASTS - reciprocal not needed
while IFS=',' read -r species strain marta dean; do
  #blastn -query ${marta} -db ${dean} -outfmt 6 -max_hsps 1 -out results/${species}_${strain}_marta_vs_dean.blast.out
  blastn -query ${dean} -db ${marta} -outfmt 6 -max_hsps 1 -out results/${species}_${strain}_dean_vs_marta.blast.out
done < <(sed '1d' curated_libs.csv)


# 
# cat("blastn -query final_curated_NR_Adri.fa -db final_curated_NR_80Simon.fa -outfmt 6 -qcov_hsp_perc 80 -perc_identity 80 -max_hsps 1 -out adri_vs_Marta.blast.out")
```

## Visualisation
```{r}
if(!require("BiocManager", character.only = T)) install.packages("BiocManager")
pkgs.list <- readLines("r-requirements.txt")

for (i in 1:length(pkgs.list)){
  if(!require(pkgs.list[i], character.only = T)){
    BiocManager::install(pkgs.list[i], Ncpus = ceiling(parallel::detectCores()/1.7))
    require(pkgs.list[i], character.only = TRUE)
  }else{require(pkgs.list[1],character.only = TRUE)}
}
```

## Load and overall comparisons
```{r}
setwd("/home/csic/gcy/jgp/extra_storage/dean/mctrials/mctrials")
source("scripts/mccompare_functions.R")

# Load the TE classifications
teClassification <- read.table("orozco_classification-2024_mchelper.csv", sep = ";", header = TRUE)
teClassification <- teClassification %>%
  mutate(AppName = paste(Class, Order, Superfamily, sep ="/") %>% sub("/$", "", .) %>% sub("/$", "", .))
teClassification <- rbind(
  teClassification
  , c("", "Unclassified", "", "Unclassified")
)

# Load libraries to compare
lib1 <- teReadLib("../../data/final_libraries/D.tristis/D.tristis.TE_library.fasta", libIdentifier = "Marta", species = "D.tristis", strain = "nanopore_D2")
lib2 <- teReadLib("data/MCH_output/D.tristis/nanopore_D2/MCH_final/final_curated_NR.fa", libIdentifier = "Dean", species = "D.tristis", strain = "nanopore_D2")

lib3 <- teReadLib("../../data/final_libraries/D.merina/D.merina.TE_library.fasta", libIdentifier = "Marta", species = "D.merina", strain = "NA")
lib4 <- teReadLib("data/MCH_output/D.merina/NA/MCH_final/final_curated_NR.fa", libIdentifier = "Dean", species = "D.merina", strain = "NA")




#D.santomea,STO_CAGO_1482_RefSeq,../../data/final_libraries/D.santomea/D.santomea.TE_library.fasta,data/MCH_output/D.santomea/STO_CAGO_1482_RefSeq/MCH_final/final_curated_NR.fa
#D.tristis,nanopore_D2,../../data/final_libraries/D.tristis/D.tristis.TE_library.fasta,data/MCH_output/D.tristis/nanopore_D2/MCH_final/final_curated_NR.fa

```

::: {.panel-tabset}
### D.tristis
```{r}
tePlotLib(list(lib2, lib1))
```

### D.merina
```{r}
tePlotLib(list(lib4, lib3))
```

:::

## Blast results


```{r}
# Load the blast results comparing curated libraries
blast1 <- LoadBlastComparison(
  blast_out = "results/D.tristis_nanopore_D2_dean_vs_marta.blast.out",
  blast_query_lib = lib2,
  blast_subject_lib = lib1,
  species = "D.tristis",
  strain = "nanopore_D2",
  comparison = "dean_vs_marta")

```



```{r}

# Categorise the comparions
blast1c <- blast1 %>%
  mutate(
    seq_match = case_when(
      pident == 100 & evalue == 0 ~ "Perfect",
      between(pident, 80, 99) ~ "Good",
      pident == 50 ~ "Moderate",
      pident == 30 ~ "Bad",
      pident == 10 ~ "Really bad",
      sseqid == NA ~ "Unique to query lib",
      qseqid == NA ~ "Unique to subject lib"
    ),
    class_match = case_when(
        q_subfamily == s_subfamily ~ "3",
        q_family == s_family & q_subfamily != s_subfamily ~ "2",
        q_class == s_class & q_family != s_family & q_subfamily != s_subfamily ~ "1",
        qseqid == NA | sseqid == NA ~ "0"
      )
  )



```